[package]
name = "instrument_communication"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.8.1"
lazy_static="1.4.0"
hostname = "^0.3"
visa={ path = "../visa" }
dlopen = "0.1.8"
log = "0.4"
env_logger = "0.10.0"

[dev-dependencies]
test-case = "3.1.0"